project:
  type: website
  output-dir: docs

website:
  title: "ECE 484 — GRAIC"
  navbar:
    background: dark

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
